apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc # from the statefulsets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
